### ISSUE TITLE
Importing an application node, does not install the application.

### ISSUE THREAD

**Issue by poi33** [GlennRicaud/data-toolbox-app#112] opened 2019-02-04 13:18 UTC
Using the Node exports to upload an application does not install the application on the server.
Work around: restart server.

**Comment by GlennRicaud** [comment] 2019-06-11 18:40
Yes it is the intended behaviour. By going directly at node level, you bypass the application mechanisms.
If this should be done, it should be done at XP level. Closing this issue

**Closed by GlennRicaud** 2019-06-11 18:40 UTC
